---
name: Continuous Integration Build

on:
    push:
        branches:
            - main
            - 2.x
            - flaky_pause_resume_test
        paths-ignore:
            - '.github/**'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [
                    {'version': '8'},
                    {'version': '11'},
                    {
                        'version': '16',
                        'opts': '--illegal-access=permit' # required for kotlin
                    },
                    {
                        'version': '17-ea',
                        'opts': '--illegal-access=permit' # required for kotlin
                    }
                ]
        name: Build with Java ${{ matrix.java.version }}
        steps:
            - uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      maven-
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  java-version: ${{ matrix.java.version }}
                  distribution: temurin
            - name: Build with Maven
              env:
                  MAVEN_OPTS: ${{ matrix.java.opts }}
              run: |
                  mvn -s .github/ci-maven-settings.xml -B \
                    clean verify -Dtest-containers=true

    quality:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      maven-
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: temurin
            - name: Coverage and Sonar
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
              run: |
                    mvn -s .github/ci-maven-settings.xml -B \
                        clean verify sonar:sonar -Pcoverage \
                        -Dsonar.projectKey=smallrye_smallrye-reactive-messaging \
                        -Dsonar.projectName="SmallRye Reactive Messaging" \
                        -Dsonar.organization=smallrye \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.login=$SONAR_LOGIN \
                        --fail-at-end

    up_to_date_antora:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: temurin
            - name: Build with Maven
              run: | # Fail the build is the antora.yaml becomes out of date
                  mvn -s .github/ci-maven-settings.xml -B install -DskipTests
                  mvn -s .github/ci-maven-settings.xml -B \
                     -pl documentation scm:check-local-modification \
                     -Dincludes=src/main/doc/antora.yml
